# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /ACGC-PC-Port/droidports

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /ACGC-PC-Port/droidports

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /ACGC-PC-Port/droidports/CMakeFiles /ACGC-PC-Port/droidports//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /ACGC-PC-Port/droidports/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lswtcs

# Build rule for target.
lswtcs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lswtcs
.PHONY : lswtcs

# fast build rule for target.
lswtcs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/build
.PHONY : lswtcs/fast

bridges/ctype_bridge.o: bridges/ctype_bridge.c.o

.PHONY : bridges/ctype_bridge.o

# target to build an object file
bridges/ctype_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/ctype_bridge.c.o
.PHONY : bridges/ctype_bridge.c.o

bridges/ctype_bridge.i: bridges/ctype_bridge.c.i

.PHONY : bridges/ctype_bridge.i

# target to preprocess a source file
bridges/ctype_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/ctype_bridge.c.i
.PHONY : bridges/ctype_bridge.c.i

bridges/ctype_bridge.s: bridges/ctype_bridge.c.s

.PHONY : bridges/ctype_bridge.s

# target to generate assembly for a file
bridges/ctype_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/ctype_bridge.c.s
.PHONY : bridges/ctype_bridge.c.s

bridges/gles2_bridge.o: bridges/gles2_bridge.c.o

.PHONY : bridges/gles2_bridge.o

# target to build an object file
bridges/gles2_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/gles2_bridge.c.o
.PHONY : bridges/gles2_bridge.c.o

bridges/gles2_bridge.i: bridges/gles2_bridge.c.i

.PHONY : bridges/gles2_bridge.i

# target to preprocess a source file
bridges/gles2_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/gles2_bridge.c.i
.PHONY : bridges/gles2_bridge.c.i

bridges/gles2_bridge.s: bridges/gles2_bridge.c.s

.PHONY : bridges/gles2_bridge.s

# target to generate assembly for a file
bridges/gles2_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/gles2_bridge.c.s
.PHONY : bridges/gles2_bridge.c.s

bridges/math_bridge.o: bridges/math_bridge.c.o

.PHONY : bridges/math_bridge.o

# target to build an object file
bridges/math_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/math_bridge.c.o
.PHONY : bridges/math_bridge.c.o

bridges/math_bridge.i: bridges/math_bridge.c.i

.PHONY : bridges/math_bridge.i

# target to preprocess a source file
bridges/math_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/math_bridge.c.i
.PHONY : bridges/math_bridge.c.i

bridges/math_bridge.s: bridges/math_bridge.c.s

.PHONY : bridges/math_bridge.s

# target to generate assembly for a file
bridges/math_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/math_bridge.c.s
.PHONY : bridges/math_bridge.c.s

bridges/misc_bridges.o: bridges/misc_bridges.c.o

.PHONY : bridges/misc_bridges.o

# target to build an object file
bridges/misc_bridges.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/misc_bridges.c.o
.PHONY : bridges/misc_bridges.c.o

bridges/misc_bridges.i: bridges/misc_bridges.c.i

.PHONY : bridges/misc_bridges.i

# target to preprocess a source file
bridges/misc_bridges.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/misc_bridges.c.i
.PHONY : bridges/misc_bridges.c.i

bridges/misc_bridges.s: bridges/misc_bridges.c.s

.PHONY : bridges/misc_bridges.s

# target to generate assembly for a file
bridges/misc_bridges.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/misc_bridges.c.s
.PHONY : bridges/misc_bridges.c.s

bridges/openal_bridge.o: bridges/openal_bridge.c.o

.PHONY : bridges/openal_bridge.o

# target to build an object file
bridges/openal_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/openal_bridge.c.o
.PHONY : bridges/openal_bridge.c.o

bridges/openal_bridge.i: bridges/openal_bridge.c.i

.PHONY : bridges/openal_bridge.i

# target to preprocess a source file
bridges/openal_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/openal_bridge.c.i
.PHONY : bridges/openal_bridge.c.i

bridges/openal_bridge.s: bridges/openal_bridge.c.s

.PHONY : bridges/openal_bridge.s

# target to generate assembly for a file
bridges/openal_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/openal_bridge.c.s
.PHONY : bridges/openal_bridge.c.s

bridges/pthread_bridge.o: bridges/pthread_bridge.c.o

.PHONY : bridges/pthread_bridge.o

# target to build an object file
bridges/pthread_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/pthread_bridge.c.o
.PHONY : bridges/pthread_bridge.c.o

bridges/pthread_bridge.i: bridges/pthread_bridge.c.i

.PHONY : bridges/pthread_bridge.i

# target to preprocess a source file
bridges/pthread_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/pthread_bridge.c.i
.PHONY : bridges/pthread_bridge.c.i

bridges/pthread_bridge.s: bridges/pthread_bridge.c.s

.PHONY : bridges/pthread_bridge.s

# target to generate assembly for a file
bridges/pthread_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/pthread_bridge.c.s
.PHONY : bridges/pthread_bridge.c.s

bridges/stdio_bridge.o: bridges/stdio_bridge.c.o

.PHONY : bridges/stdio_bridge.o

# target to build an object file
bridges/stdio_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/stdio_bridge.c.o
.PHONY : bridges/stdio_bridge.c.o

bridges/stdio_bridge.i: bridges/stdio_bridge.c.i

.PHONY : bridges/stdio_bridge.i

# target to preprocess a source file
bridges/stdio_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/stdio_bridge.c.i
.PHONY : bridges/stdio_bridge.c.i

bridges/stdio_bridge.s: bridges/stdio_bridge.c.s

.PHONY : bridges/stdio_bridge.s

# target to generate assembly for a file
bridges/stdio_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/stdio_bridge.c.s
.PHONY : bridges/stdio_bridge.c.s

bridges/zip_bridge.o: bridges/zip_bridge.c.o

.PHONY : bridges/zip_bridge.o

# target to build an object file
bridges/zip_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/zip_bridge.c.o
.PHONY : bridges/zip_bridge.c.o

bridges/zip_bridge.i: bridges/zip_bridge.c.i

.PHONY : bridges/zip_bridge.i

# target to preprocess a source file
bridges/zip_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/zip_bridge.c.i
.PHONY : bridges/zip_bridge.c.i

bridges/zip_bridge.s: bridges/zip_bridge.c.s

.PHONY : bridges/zip_bridge.s

# target to generate assembly for a file
bridges/zip_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/bridges/zip_bridge.c.s
.PHONY : bridges/zip_bridge.c.s

jni/JString.o: jni/JString.c.o

.PHONY : jni/JString.o

# target to build an object file
jni/JString.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/JString.c.o
.PHONY : jni/JString.c.o

jni/JString.i: jni/JString.c.i

.PHONY : jni/JString.i

# target to preprocess a source file
jni/JString.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/JString.c.i
.PHONY : jni/JString.c.i

jni/JString.s: jni/JString.c.s

.PHONY : jni/JString.s

# target to generate assembly for a file
jni/JString.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/JString.c.s
.PHONY : jni/JString.c.s

jni/fake_jni.o: jni/fake_jni.c.o

.PHONY : jni/fake_jni.o

# target to build an object file
jni/fake_jni.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/fake_jni.c.o
.PHONY : jni/fake_jni.c.o

jni/fake_jni.i: jni/fake_jni.c.i

.PHONY : jni/fake_jni.i

# target to preprocess a source file
jni/fake_jni.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/fake_jni.c.i
.PHONY : jni/fake_jni.c.i

jni/fake_jni.s: jni/fake_jni.c.s

.PHONY : jni/fake_jni.s

# target to generate assembly for a file
jni/fake_jni.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/fake_jni.c.s
.PHONY : jni/fake_jni.c.s

jni/os_Build.o: jni/os_Build.c.o

.PHONY : jni/os_Build.o

# target to build an object file
jni/os_Build.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/os_Build.c.o
.PHONY : jni/os_Build.c.o

jni/os_Build.i: jni/os_Build.c.i

.PHONY : jni/os_Build.i

# target to preprocess a source file
jni/os_Build.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/os_Build.c.i
.PHONY : jni/os_Build.c.i

jni/os_Build.s: jni/os_Build.c.s

.PHONY : jni/os_Build.s

# target to generate assembly for a file
jni/os_Build.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/jni/os_Build.c.s
.PHONY : jni/os_Build.c.s

platform/common/crc32.o: platform/common/crc32.c.o

.PHONY : platform/common/crc32.o

# target to build an object file
platform/common/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/crc32.c.o
.PHONY : platform/common/crc32.c.o

platform/common/crc32.i: platform/common/crc32.c.i

.PHONY : platform/common/crc32.i

# target to preprocess a source file
platform/common/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/crc32.c.i
.PHONY : platform/common/crc32.c.i

platform/common/crc32.s: platform/common/crc32.c.s

.PHONY : platform/common/crc32.s

# target to generate assembly for a file
platform/common/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/crc32.c.s
.PHONY : platform/common/crc32.c.s

platform/common/gles2_loader.o: platform/common/gles2_loader.c.o

.PHONY : platform/common/gles2_loader.o

# target to build an object file
platform/common/gles2_loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/gles2_loader.c.o
.PHONY : platform/common/gles2_loader.c.o

platform/common/gles2_loader.i: platform/common/gles2_loader.c.i

.PHONY : platform/common/gles2_loader.i

# target to preprocess a source file
platform/common/gles2_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/gles2_loader.c.i
.PHONY : platform/common/gles2_loader.c.i

platform/common/gles2_loader.s: platform/common/gles2_loader.c.s

.PHONY : platform/common/gles2_loader.s

# target to generate assembly for a file
platform/common/gles2_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/gles2_loader.c.s
.PHONY : platform/common/gles2_loader.c.s

platform/common/io_util.o: platform/common/io_util.c.o

.PHONY : platform/common/io_util.o

# target to build an object file
platform/common/io_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/io_util.c.o
.PHONY : platform/common/io_util.c.o

platform/common/io_util.i: platform/common/io_util.c.i

.PHONY : platform/common/io_util.i

# target to preprocess a source file
platform/common/io_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/io_util.c.i
.PHONY : platform/common/io_util.c.i

platform/common/io_util.s: platform/common/io_util.c.s

.PHONY : platform/common/io_util.s

# target to generate assembly for a file
platform/common/io_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/io_util.c.s
.PHONY : platform/common/io_util.c.s

platform/common/so_util.o: platform/common/so_util.c.o

.PHONY : platform/common/so_util.o

# target to build an object file
platform/common/so_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/so_util.c.o
.PHONY : platform/common/so_util.c.o

platform/common/so_util.i: platform/common/so_util.c.i

.PHONY : platform/common/so_util.i

# target to preprocess a source file
platform/common/so_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/so_util.c.i
.PHONY : platform/common/so_util.c.i

platform/common/so_util.s: platform/common/so_util.c.s

.PHONY : platform/common/so_util.s

# target to generate assembly for a file
platform/common/so_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/so_util.c.s
.PHONY : platform/common/so_util.c.s

platform/common/zip_util.o: platform/common/zip_util.c.o

.PHONY : platform/common/zip_util.o

# target to build an object file
platform/common/zip_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/zip_util.c.o
.PHONY : platform/common/zip_util.c.o

platform/common/zip_util.i: platform/common/zip_util.c.i

.PHONY : platform/common/zip_util.i

# target to preprocess a source file
platform/common/zip_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/zip_util.c.i
.PHONY : platform/common/zip_util.c.i

platform/common/zip_util.s: platform/common/zip_util.c.s

.PHONY : platform/common/zip_util.s

# target to generate assembly for a file
platform/common/zip_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/common/zip_util.c.s
.PHONY : platform/common/zip_util.c.s

platform/linux/physram.o: platform/linux/physram.c.o

.PHONY : platform/linux/physram.o

# target to build an object file
platform/linux/physram.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/physram.c.o
.PHONY : platform/linux/physram.c.o

platform/linux/physram.i: platform/linux/physram.c.i

.PHONY : platform/linux/physram.i

# target to preprocess a source file
platform/linux/physram.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/physram.c.i
.PHONY : platform/linux/physram.c.i

platform/linux/physram.s: platform/linux/physram.c.s

.PHONY : platform/linux/physram.s

# target to generate assembly for a file
platform/linux/physram.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/physram.c.s
.PHONY : platform/linux/physram.c.s

platform/linux/so_util_linux.o: platform/linux/so_util_linux.c.o

.PHONY : platform/linux/so_util_linux.o

# target to build an object file
platform/linux/so_util_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/so_util_linux.c.o
.PHONY : platform/linux/so_util_linux.c.o

platform/linux/so_util_linux.i: platform/linux/so_util_linux.c.i

.PHONY : platform/linux/so_util_linux.i

# target to preprocess a source file
platform/linux/so_util_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/so_util_linux.c.i
.PHONY : platform/linux/so_util_linux.c.i

platform/linux/so_util_linux.s: platform/linux/so_util_linux.c.s

.PHONY : platform/linux/so_util_linux.s

# target to generate assembly for a file
platform/linux/so_util_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/platform/linux/so_util_linux.c.s
.PHONY : platform/linux/so_util_linux.c.s

ports/lswtcs/TTActivity.o: ports/lswtcs/TTActivity.c.o

.PHONY : ports/lswtcs/TTActivity.o

# target to build an object file
ports/lswtcs/TTActivity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/TTActivity.c.o
.PHONY : ports/lswtcs/TTActivity.c.o

ports/lswtcs/TTActivity.i: ports/lswtcs/TTActivity.c.i

.PHONY : ports/lswtcs/TTActivity.i

# target to preprocess a source file
ports/lswtcs/TTActivity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/TTActivity.c.i
.PHONY : ports/lswtcs/TTActivity.c.i

ports/lswtcs/TTActivity.s: ports/lswtcs/TTActivity.c.s

.PHONY : ports/lswtcs/TTActivity.s

# target to generate assembly for a file
ports/lswtcs/TTActivity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/TTActivity.c.s
.PHONY : ports/lswtcs/TTActivity.c.s

ports/lswtcs/asset_manager.o: ports/lswtcs/asset_manager.c.o

.PHONY : ports/lswtcs/asset_manager.o

# target to build an object file
ports/lswtcs/asset_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/asset_manager.c.o
.PHONY : ports/lswtcs/asset_manager.c.o

ports/lswtcs/asset_manager.i: ports/lswtcs/asset_manager.c.i

.PHONY : ports/lswtcs/asset_manager.i

# target to preprocess a source file
ports/lswtcs/asset_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/asset_manager.c.i
.PHONY : ports/lswtcs/asset_manager.c.i

ports/lswtcs/asset_manager.s: ports/lswtcs/asset_manager.c.s

.PHONY : ports/lswtcs/asset_manager.s

# target to generate assembly for a file
ports/lswtcs/asset_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/asset_manager.c.s
.PHONY : ports/lswtcs/asset_manager.c.s

ports/lswtcs/cursor_overlay.o: ports/lswtcs/cursor_overlay.c.o

.PHONY : ports/lswtcs/cursor_overlay.o

# target to build an object file
ports/lswtcs/cursor_overlay.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/cursor_overlay.c.o
.PHONY : ports/lswtcs/cursor_overlay.c.o

ports/lswtcs/cursor_overlay.i: ports/lswtcs/cursor_overlay.c.i

.PHONY : ports/lswtcs/cursor_overlay.i

# target to preprocess a source file
ports/lswtcs/cursor_overlay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/cursor_overlay.c.i
.PHONY : ports/lswtcs/cursor_overlay.c.i

ports/lswtcs/cursor_overlay.s: ports/lswtcs/cursor_overlay.c.s

.PHONY : ports/lswtcs/cursor_overlay.s

# target to generate assembly for a file
ports/lswtcs/cursor_overlay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/cursor_overlay.c.s
.PHONY : ports/lswtcs/cursor_overlay.c.s

ports/lswtcs/io_remap.o: ports/lswtcs/io_remap.c.o

.PHONY : ports/lswtcs/io_remap.o

# target to build an object file
ports/lswtcs/io_remap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/io_remap.c.o
.PHONY : ports/lswtcs/io_remap.c.o

ports/lswtcs/io_remap.i: ports/lswtcs/io_remap.c.i

.PHONY : ports/lswtcs/io_remap.i

# target to preprocess a source file
ports/lswtcs/io_remap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/io_remap.c.i
.PHONY : ports/lswtcs/io_remap.c.i

ports/lswtcs/io_remap.s: ports/lswtcs/io_remap.c.s

.PHONY : ports/lswtcs/io_remap.s

# target to generate assembly for a file
ports/lswtcs/io_remap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/io_remap.c.s
.PHONY : ports/lswtcs/io_remap.c.s

ports/lswtcs/libtt.o: ports/lswtcs/libtt.c.o

.PHONY : ports/lswtcs/libtt.o

# target to build an object file
ports/lswtcs/libtt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/libtt.c.o
.PHONY : ports/lswtcs/libtt.c.o

ports/lswtcs/libtt.i: ports/lswtcs/libtt.c.i

.PHONY : ports/lswtcs/libtt.i

# target to preprocess a source file
ports/lswtcs/libtt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/libtt.c.i
.PHONY : ports/lswtcs/libtt.c.i

ports/lswtcs/libtt.s: ports/lswtcs/libtt.c.s

.PHONY : ports/lswtcs/libtt.s

# target to generate assembly for a file
ports/lswtcs/libtt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/libtt.c.s
.PHONY : ports/lswtcs/libtt.c.s

ports/lswtcs/main.o: ports/lswtcs/main.c.o

.PHONY : ports/lswtcs/main.o

# target to build an object file
ports/lswtcs/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/main.c.o
.PHONY : ports/lswtcs/main.c.o

ports/lswtcs/main.i: ports/lswtcs/main.c.i

.PHONY : ports/lswtcs/main.i

# target to preprocess a source file
ports/lswtcs/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/main.c.i
.PHONY : ports/lswtcs/main.c.i

ports/lswtcs/main.s: ports/lswtcs/main.c.s

.PHONY : ports/lswtcs/main.s

# target to generate assembly for a file
ports/lswtcs/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/main.c.s
.PHONY : ports/lswtcs/main.c.s

ports/lswtcs/opensles_bridge.o: ports/lswtcs/opensles_bridge.c.o

.PHONY : ports/lswtcs/opensles_bridge.o

# target to build an object file
ports/lswtcs/opensles_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/opensles_bridge.c.o
.PHONY : ports/lswtcs/opensles_bridge.c.o

ports/lswtcs/opensles_bridge.i: ports/lswtcs/opensles_bridge.c.i

.PHONY : ports/lswtcs/opensles_bridge.i

# target to preprocess a source file
ports/lswtcs/opensles_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/opensles_bridge.c.i
.PHONY : ports/lswtcs/opensles_bridge.c.i

ports/lswtcs/opensles_bridge.s: ports/lswtcs/opensles_bridge.c.s

.PHONY : ports/lswtcs/opensles_bridge.s

# target to generate assembly for a file
ports/lswtcs/opensles_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/opensles_bridge.c.s
.PHONY : ports/lswtcs/opensles_bridge.c.s

ports/lswtcs/patch.o: ports/lswtcs/patch.c.o

.PHONY : ports/lswtcs/patch.o

# target to build an object file
ports/lswtcs/patch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/patch.c.o
.PHONY : ports/lswtcs/patch.c.o

ports/lswtcs/patch.i: ports/lswtcs/patch.c.i

.PHONY : ports/lswtcs/patch.i

# target to preprocess a source file
ports/lswtcs/patch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/patch.c.i
.PHONY : ports/lswtcs/patch.c.i

ports/lswtcs/patch.s: ports/lswtcs/patch.c.s

.PHONY : ports/lswtcs/patch.s

# target to generate assembly for a file
ports/lswtcs/patch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/patch.c.s
.PHONY : ports/lswtcs/patch.c.s

ports/lswtcs/sdl2_media.o: ports/lswtcs/sdl2_media.c.o

.PHONY : ports/lswtcs/sdl2_media.o

# target to build an object file
ports/lswtcs/sdl2_media.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/sdl2_media.c.o
.PHONY : ports/lswtcs/sdl2_media.c.o

ports/lswtcs/sdl2_media.i: ports/lswtcs/sdl2_media.c.i

.PHONY : ports/lswtcs/sdl2_media.i

# target to preprocess a source file
ports/lswtcs/sdl2_media.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/sdl2_media.c.i
.PHONY : ports/lswtcs/sdl2_media.c.i

ports/lswtcs/sdl2_media.s: ports/lswtcs/sdl2_media.c.s

.PHONY : ports/lswtcs/sdl2_media.s

# target to generate assembly for a file
ports/lswtcs/sdl2_media.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/sdl2_media.c.s
.PHONY : ports/lswtcs/sdl2_media.c.s

ports/lswtcs/symtable_lswtcs.o: ports/lswtcs/symtable_lswtcs.c.o

.PHONY : ports/lswtcs/symtable_lswtcs.o

# target to build an object file
ports/lswtcs/symtable_lswtcs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/symtable_lswtcs.c.o
.PHONY : ports/lswtcs/symtable_lswtcs.c.o

ports/lswtcs/symtable_lswtcs.i: ports/lswtcs/symtable_lswtcs.c.i

.PHONY : ports/lswtcs/symtable_lswtcs.i

# target to preprocess a source file
ports/lswtcs/symtable_lswtcs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/symtable_lswtcs.c.i
.PHONY : ports/lswtcs/symtable_lswtcs.c.i

ports/lswtcs/symtable_lswtcs.s: ports/lswtcs/symtable_lswtcs.c.s

.PHONY : ports/lswtcs/symtable_lswtcs.s

# target to generate assembly for a file
ports/lswtcs/symtable_lswtcs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lswtcs.dir/build.make CMakeFiles/lswtcs.dir/ports/lswtcs/symtable_lswtcs.c.s
.PHONY : ports/lswtcs/symtable_lswtcs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lswtcs"
	@echo "... bridges/ctype_bridge.o"
	@echo "... bridges/ctype_bridge.i"
	@echo "... bridges/ctype_bridge.s"
	@echo "... bridges/gles2_bridge.o"
	@echo "... bridges/gles2_bridge.i"
	@echo "... bridges/gles2_bridge.s"
	@echo "... bridges/math_bridge.o"
	@echo "... bridges/math_bridge.i"
	@echo "... bridges/math_bridge.s"
	@echo "... bridges/misc_bridges.o"
	@echo "... bridges/misc_bridges.i"
	@echo "... bridges/misc_bridges.s"
	@echo "... bridges/openal_bridge.o"
	@echo "... bridges/openal_bridge.i"
	@echo "... bridges/openal_bridge.s"
	@echo "... bridges/pthread_bridge.o"
	@echo "... bridges/pthread_bridge.i"
	@echo "... bridges/pthread_bridge.s"
	@echo "... bridges/stdio_bridge.o"
	@echo "... bridges/stdio_bridge.i"
	@echo "... bridges/stdio_bridge.s"
	@echo "... bridges/zip_bridge.o"
	@echo "... bridges/zip_bridge.i"
	@echo "... bridges/zip_bridge.s"
	@echo "... jni/JString.o"
	@echo "... jni/JString.i"
	@echo "... jni/JString.s"
	@echo "... jni/fake_jni.o"
	@echo "... jni/fake_jni.i"
	@echo "... jni/fake_jni.s"
	@echo "... jni/os_Build.o"
	@echo "... jni/os_Build.i"
	@echo "... jni/os_Build.s"
	@echo "... platform/common/crc32.o"
	@echo "... platform/common/crc32.i"
	@echo "... platform/common/crc32.s"
	@echo "... platform/common/gles2_loader.o"
	@echo "... platform/common/gles2_loader.i"
	@echo "... platform/common/gles2_loader.s"
	@echo "... platform/common/io_util.o"
	@echo "... platform/common/io_util.i"
	@echo "... platform/common/io_util.s"
	@echo "... platform/common/so_util.o"
	@echo "... platform/common/so_util.i"
	@echo "... platform/common/so_util.s"
	@echo "... platform/common/zip_util.o"
	@echo "... platform/common/zip_util.i"
	@echo "... platform/common/zip_util.s"
	@echo "... platform/linux/physram.o"
	@echo "... platform/linux/physram.i"
	@echo "... platform/linux/physram.s"
	@echo "... platform/linux/so_util_linux.o"
	@echo "... platform/linux/so_util_linux.i"
	@echo "... platform/linux/so_util_linux.s"
	@echo "... ports/lswtcs/TTActivity.o"
	@echo "... ports/lswtcs/TTActivity.i"
	@echo "... ports/lswtcs/TTActivity.s"
	@echo "... ports/lswtcs/asset_manager.o"
	@echo "... ports/lswtcs/asset_manager.i"
	@echo "... ports/lswtcs/asset_manager.s"
	@echo "... ports/lswtcs/cursor_overlay.o"
	@echo "... ports/lswtcs/cursor_overlay.i"
	@echo "... ports/lswtcs/cursor_overlay.s"
	@echo "... ports/lswtcs/io_remap.o"
	@echo "... ports/lswtcs/io_remap.i"
	@echo "... ports/lswtcs/io_remap.s"
	@echo "... ports/lswtcs/libtt.o"
	@echo "... ports/lswtcs/libtt.i"
	@echo "... ports/lswtcs/libtt.s"
	@echo "... ports/lswtcs/main.o"
	@echo "... ports/lswtcs/main.i"
	@echo "... ports/lswtcs/main.s"
	@echo "... ports/lswtcs/opensles_bridge.o"
	@echo "... ports/lswtcs/opensles_bridge.i"
	@echo "... ports/lswtcs/opensles_bridge.s"
	@echo "... ports/lswtcs/patch.o"
	@echo "... ports/lswtcs/patch.i"
	@echo "... ports/lswtcs/patch.s"
	@echo "... ports/lswtcs/sdl2_media.o"
	@echo "... ports/lswtcs/sdl2_media.i"
	@echo "... ports/lswtcs/sdl2_media.s"
	@echo "... ports/lswtcs/symtable_lswtcs.o"
	@echo "... ports/lswtcs/symtable_lswtcs.i"
	@echo "... ports/lswtcs/symtable_lswtcs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

